language: python
sudo: false
cache: pip


python:
  - 3.4
  - 3.5
  - 3.6
  - pypy3.5

matrix:
  include:
    - python: 3.7
      env: TEST_REQUIRE=fastimport
      dist: xenial

install:
  - apt install devscripts brz-debian python3-breezy python3-dulwich python3-github python3-gitlab python3-launchpadlib python3-flake8

script:
  - make check
